eforminternal/eform/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'eform'
urlpatterns = [
    path('tab_coform/', views.tab_coform, name='tab_coform'),
    path('tab_daily/', views.tab_daily, name='tab_daily'),
    path('tab_cashpymt/', views.tab_cashpymt, name='tab_cashpymt'),
    path('tab_search/', views.tab_search, name='tab_search'),
    path('tab_search/daily/', views.daily, name='daily'),
    path('tab_search/mailOrder/', views.mailOrder, name='mailOrder'),
    path('tab_search/cashPymt/', views.cashPymt, name='cashPymt'),
    path('login/', auth_views.LoginView.as_view(template_name='myweb/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='myweb/logout.html'), name='logout'),
    path('index/', views.index, name='index'),
]

eforminternal/eform_internal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import static ##新增
from django.conf import settings ##新增
from django.conf.urls import url ##新增


urlpatterns = [
    path('eform/admin/', admin.site.urls),
    path('eform/', include('eform.urls', namespace='eform')),
    url(r'^static/(?P<path>.*)$', static.serve,
        {'document_root': settings.STATIC_ROOT}, name='static'),
    # url(r'^', include(router.urls)),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

eforminternal/templates/myweb/base.html
{% load static %}
{% if  request.user.is_authenticated %}
<head>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<div class="base navbar">
    <div class="navbar_logo">
        <img src="{% static 'img/logo.png' %}" at="logo">
    </div>
    <div class="navbar_link">
        <!-- <div class="navbar_link_item">
            <a href="{% url "eform:tab_daily" %}">每日必填</a>
        </div> -->
        <div class="navbar_link_item">
            <a href="{% url "eform:tab_coform" %}">郵購單</a>
        </div>
        <div class="navbar_link_item">
            <a href="{% url "eform:tab_cashpymt" %}">現金匯款單</a>
        </div>
        {% if  request.user.is_superuser %}
        <div class="navbar_link_item">
            <a href="{% url "eform:mailOrder" %}">查詢</a>
        </div>
        {% endif %}
        <div class="navbar_link_user">
            <div class="navbar_link_user_side">
                <label></label>
                <p id="navbar_link_userId">{{ request.user.first_name }}</p>
                <p id="navbar_link_userName">{{ request.user.last_name }}</p>
            </div>
            <div class="navbar_link_userControl" style="display: none;">
                <a href="{% url "eform:logout" %}">登出</a>
            </div>
        </div>
<!--         
        {% else %}
        <a href="{% url "eform:login" %}">Login</a>
        {% endif %} -->
    </div>
</div>

<div class="page_background noPrint">
    <div class="bgc"></div>
    <img class="noPrint" src="{% static 'img/background.jpg' %}" at="login_background">
</div>

{% block content %}
{% endblock %}


<script src="{% static 'js/reference/jquery.js' %}"></script>

<script>
    const $user = $('.navbar .navbar_link_user');
    $user.on('click', function () {
        $('.navbar .navbar_link_userControl').toggle();
    })

</script>

eforminternal/templates/myweb/cashPymt.html
{% extends "myweb/base.html" %}

{% block content %}
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/reference/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/reference/fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
</head>
<section class="page search" id="Search">

    <header class="pageNavBar">
        <!-- <a href="{% url "eform:daily" %}">
            <div class="pageNavBar_item button" data-id="search_daily">每日必填</div>
        </a> -->
        <a href="{% url "eform:mailOrder" %}">
            <div class="pageNavBar_item button" data-id="search_coform" data-name="mailorder">郵購單</div>
        </a>
        <a href="{% url "eform:cashPymt" %}">
            <div class="pageNavBar_item button active" data-id="search_cashpymt" data-name="cashpymt">現金匯款單</div>
        </a>
    </header>
    <div class="block condition_block">
        <h1 class="title">請選擇搜尋條件</h1>
        <form class="search_cashpymt search_main" method="POST">

            <label class="search_item">
                <input type="checkbox" name="selection4" data-name="status" disabled="disabled" checked style="opacity: 0;">
                <div class="search_item_main">
                    <h4>付款單狀態</h4>
                    <div class="search_item_main_value">
                        <div class="selectBox">
                            <i class="fas fa-angle-down"></i>
                            <select id="Cashpymt_status" name="status" class="block_form_item_select checkedValueBox condition_value">
                                <option value="已送出">已送出</option>
                                <option value="未送出">未送出</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="search_item_bgc"></div>
            </label>
            <label class="search_item">
                <input type="checkbox" name="selection1" class="condition" id="Cashpymt_store" data-name="store_name">
                <div class="search_item_main">
                    <h4>分店名稱</h4>
                    <div class="search_item_main_value">
                        <div class="selectBox">
                            <i class="fas fa-angle-down"></i>
                            <select name="store_name" class="block_form_item_select storeList checkedValueBox condition_value" disabled="disabled">
                                <option value="CA">CA / 南京店</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="search_item_bgc"></div>
            </label>
            <label class="search_item search_item_date">
                <input type="checkbox" name="selection3" class="condition" id="Cashpymt_getCashDate" data-name="data_src_date">
                <div class="search_item_main">
                    <h4>付款單日期</h4>
                    <div class="dateBox">
                        <div class="picker">
                            <input type="date" name="data_src_date_from" class="datepicker checkedValueBox condition_value" disabled="disabled">
                            <i class="far fa-calendar"></i>
                        </div>
                        -
                        <div class="picker">
                            <input type="date" name="data_src_date_to" class="datepicker checkedValueBox condition_value" disabled="disabled">
                            <i class="far fa-calendar"></i>
                        </div>
                    </div>
                </div>
                <div class="search_item_bgc"></div>
            </label>
            <label class="search_item">
                <input type="checkbox" name="selection4" class="condition" id="Cashpymt_clientName" data-name="cust_name">
                <div class="search_item_main">
                    <h4>會員姓名</h4>
                    <div class="search_item_main_value">
                        <input type="text" name="cust_name" class="block_form_item_input checkedValueBox condition_value" disabled="disabled">
                    </div>
                </div>
                <div class="search_item_bgc"></div>
            </label>

            <div class="sendCondition">
                <label class="search_item search_item_date">
                    <input type="checkbox" name="selection2" class="condition" id="Cashpymt_getCodeDate" data-name="deposit_date">
                    <div class="search_item_main">
                        <h4>匯款日期</h4>
                        <div class="dateBox">
                            <div class="picker">
                                <input type="date" name="deposit_date_from" class="datepicker checkedValueBox condition_value" disabled="disabled">
                                <i class="far fa-calendar"></i>
                            </div>
                            -
                            <div class="picker">
                                <input type="date" name="deposit_date_to" class="datepicker checkedValueBox condition_value" disabled="disabled">
                                <i class="far fa-calendar"></i>
                            </div>
                        </div>
                    </div>
                    <div class="search_item_bgc"></div>
                </label>
            </div>

            <div class="notSendCondition" style="display: none;">
                <label class="search_item search_item_date">
                    <input type="checkbox" name="selection2" class="condition" data-name="pymt_date">
                    <div class="search_item_main">
                        <h4>付款日期</h4>
                        <div class="dateBox">
                            <div class="picker">
                                <input type="date" name="pymt_date_from" class="datepicker checkedValueBox condition_value" disabled="disabled">
                                <i class="far fa-calendar"></i>
                            </div>
                            -
                            <div class="picker">
                                <input type="date" name="pymt_date_to" class="datepicker checkedValueBox condition_value" disabled="disabled">
                                <i class="far fa-calendar"></i>
                            </div>
                        </div>
                    </div>
                    <div class="search_item_bgc"></div>
                </label>
                <label class="search_item search_item_date">
                    <input type="checkbox" name="selection2" class="condition refund_ind" data-name="refund_ind" disabled="disabled" checked style="opacity: 0;">
                    <div class="search_item_main">
                        <h4>匯款或退款</h4>
                        <div class="search_item_main_value">
                            <div class="selectBox">
                                <i class="fas fa-angle-down"></i>
                                <select id="Cashpymt_refund_ind" name="refund_ind" class="block_form_item_select checkedValueBox condition_value refund_ind" disabled="disabled">
                                    <option value="0">匯款</option>
                                    <option value="1">退款</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="search_item_bgc"></div>
                </label>
            </div>
            
            <p><input type="submit" class="button" value="查詢"></p>
    {% csrf_token %}
        </form>
    </div>

    <div class="block result" id="search_cashpymt" style="display: none;">
        <div class="tableBlock">
            <table>
                <thead>
                    <tr>
                        <th id="operation">操作</th>
                        <th id="cashPymt_id">匯款單號</th>
                        <th id="store_id">分店編號</th>
                        <th id="store_name">分店名稱</th>
                        <th id="cust_id">會員編號</th>
                        <th id="cust_name">會員姓名</th>
                        <th id="data_src_date">付款單日期</th>
                        <th id="pymt_order_id">付款單號</th>
                        <th id="pymt_order_seq">付款單明細</th>
                        <th id="pymt_amt">付款金額</th>
                        <th id="deposit_date">匯款日期</th>
                        <th id="r_id">匯款人工號</th>
                        <th id="r_name">匯款人名稱</th>
                        <th id="data_dttm">資料時間</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>

        <div class="buttons">
            <button class="button" id="Export">匯出 Excel</button>
        </div>
    </div>

</section>

<div id="alert">
    <div class="alertBg"></div>
    <div class="alertmain">
        <svg width="100" height="100" class="icon">
            <circle fill="#68E534" cx="50" cy="50" r="45" class="circle" />
            <polyline fill="none" stroke="#fff" stroke-width="10" points="30,55 45,70 70,35" stroke-linecap="round" stroke-linejoin="round" class="tick" />
            <g class="fork">
                <polyline fill="none" stroke="#fff" stroke-width="10" points="35,65 65,35" stroke-linecap="round" />
                <polyline fill="none" stroke="#fff" stroke-width="10" points="35,35 65,65" stroke-linecap="round" />
            </g>
        </svg>
        <div class="question_main">
            <h4>確定刪除此筆資料？</h4>
            <div class="checkBtns">
                <div class="button" data-type="true">確定</div>
                <div class="button" data-type="false">取消</div>
            </div>
        </div>
        <div class="loading"></div>
        <h3>已送出!</h3>
        <div class="errorBlock">
            <h5 class="errorBlock_btn">查看更多 ▼</h5>
            <span class="errorBlock_text"></span>
        </div>
    </div>
</div>

<script src="{% static 'js/reference/jquery.js' %}"></script>
<script src="{% static 'js/reference/papaparse.min.js' %}"></script>
<script src="{% static 'js/api.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


{% endblock %}

eforminternal/templates/myweb/daily.html
{% extends "myweb/base.html" %}

{% block content %}
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/reference/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/reference/fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
</head>
<section class="page search" id="Search">

    <header class="pageNavBar">
        <a href="{% url "eform:daily" %}">
            <div class="pageNavBar_item button active" data-id="search_daily">每日必填</div>
        </a>
        <a href="{% url "eform:mailOrder" %}">
            <div class="pageNavBar_item button" data-id="search_coform">郵購單</div>
        </a>
        <a href="{% url "eform:cashPymt" %}">
            <div class="pageNavBar_item button" data-id="search_cashpymt">現金匯款單</div>
        </a>
    </header>
    <div class="block">
        <h1 class="title">請選擇搜尋條件</h1>
        <form class="search_daily search_main" method="POST">
            <label class="search_item">
                <input type="checkbox" name="selection1" class="condition" id="Daily_store">
                <div class="search_item_main">
                    <h4>分店名稱</h4>
                    <div class="search_item_main_value">
                        <div class="selectBox">
                            <i class="fas fa-angle-down"></i>
                            <select name="store_name" class="block_form_item_select storeList checkedValueBox" disabled="disabled">
                                <option value="CA">CA / 南京店</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="search_item_bgc"></div>
            </label>
            <label class="search_item">
                <input type="checkbox" name="selection2" class="condition" id="Daily_id">
                <div class="search_item_main">
                    <h4>員工號</h4>
                    <div class="search_item_main_value">
                        <input name="r_id" type="text" class="block_form_item_input checkedValueBox" disabled="disabled">
                    </div>
                </div>
                <div class="search_item_bgc"></div>
            </label>
            <label class="search_item">
                <input type="checkbox" name="selection3" class="condition" id="Daily_date">
                <div class="search_item_main">
                    <h4>日期區間</h4>
                    <div class="dateBox">
                        <div class="picker">
                            <input type="date" name="r_date_from" class="datepicker checkedValueBox" disabled="disabled">
                            <i class="far fa-calendar"></i>
                        </div>
                        -
                        <div class="picker">
                            <input type="date" name="r_date_to" class="datepicker checkedValueBox" disabled="disabled">
                            <i class="far fa-calendar"></i>
                        </div>
                    </div>
                </div>
                <div class="search_item_bgc"></div>
            </label>
            <p><input type="submit" class="button" value="查詢"></p>
            {% csrf_token %}
        </form>
    </div>

    <div class="block result" id="search_daily">
        <table>
            <thead>
                <tr>
                    <th id="operation">操作</th>
                    <th id="item_num">單號</th>
                    <th id="store_id">分店代號</th>
                    <th id="store_name">分店名稱</th>
                    <th id="r_date">記錄日期</th>
                    <th id="on_duty">上班人數</th>
                    <th id="on_duty_name">出勤人員</th>
                    <th id="r_id">紀錄工號</th>
                    <th id="r_name">紀錄姓名</th>
                    <th id="datetimestamp">紀錄時間</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td headers="operation">
                        <button class="button">刪除</button>
                    </td>
                    <td headers="item_num">CA20210123111820</td>
                    <td headers="store_id">CA</td>
                    <td headers="store_name">南京店</td>
                    <td headers="r_date">2021-01-23</td>
                    <td headers="on_duty">9.5</td>
                    <td headers="on_duty_name">珮 惠 真 足 慧 緒0.5 詩 店 敏經 芳店</td>
                    <td headers="r_id">S18030</td>
                    <td headers="r_name">許以琳</td>
                    <td headers="datetimestamp">2021-01-23</td>
                </tr>
                <tr>
                    <td headers="operation">
                        <button class="button">刪除</button>
                    </td>
                    <td headers="item_num">CA20210123111820</td>
                    <td headers="store_id">CA</td>
                    <td headers="store_name">南京店</td>
                    <td headers="r_date">2021-01-23</td>
                    <td headers="on_duty">9.5</td>
                    <td headers="on_duty_name">珮 惠 真 足 慧 緒0.5 詩 店 敏經 芳店</td>
                    <td headers="r_id">S18030</td>
                    <td headers="r_name">許以琳</td>
                    <td headers="datetimestamp">2021-01-23</td>
                </tr>
                <tr>
                    <td headers="operation">
                        <button class="button">刪除</button>
                    </td>
                    <td headers="item_num">CA20210123111820</td>
                    <td headers="store_id">CA</td>
                    <td headers="store_name">南京店</td>
                    <td headers="r_date">2021-01-23</td>
                    <td headers="on_duty">9.5</td>
                    <td headers="on_duty_name">珮 惠 真 足 慧 緒0.5 詩 店 敏經 芳店</td>
                    <td headers="r_id">S18030</td>
                    <td headers="r_name">許以琳</td>
                    <td headers="datetimestamp">2021-01-23</td>
                </tr>
            </tbody>
        </table>

        <div class="buttons">
            <button class="button" id="Export">匯出 Excel</button>
        </div>
    </div>

</section>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="{% static 'js/api.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


{% endblock %}

eforminternal/templates/myweb/login.html
{% block content %}
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="Shortcut Icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
</head>
<div class="page_background">
    <div class="bgc"></div>
    <img src="{% static 'img/background.jpg' %}" at="login_background">
</div>
<section class="login page" id="Login">
    <div class="login_logo_block">
        <img src="{% static 'img/logo.jpg' %}" alt="logo">
    </div>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" class="button" value="登入"></p>
    </form>
</section>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>

{% endblock %}

eforminternal/templates/myweb/logout.html
{% block content %}
<h1 align="center">登出成功</h1>
{% endblock %}

eforminternal/templates/myweb/tab_cashpymt.html
{% extends "myweb/base.html" %}

{% block content %}
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/reference/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/reference/fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/cashpymt.css' %}">
</head>
<section class="cashpymt page" id="Cashpymt">
    <div class="block cashpymt_start" >
        <h1 class="title" id="cashpymt_start_title" data-num={{ cashPymt_id }} >現金匯款單</h1>
        <form class="block_form">
            <div class="block_form_item">
                <div class="block_form_item_title">
                    分店名稱
                    <span class="required">*</span>
                </div>
                <div class="selectBox">
                    <i class="fas fa-angle-down"></i>
                    <select name="unit" id="store_id" class="block_form_item_select storeList" required>
                    </select>
                </div>
            </div>
            <div class="block_form_item">
                <div class="block_form_item_title">
                    匯款單號
                </div>
                <input type="text" value="" class="block_form_item_input readonly" id="cashpymt_id" required readonly>
            </div>
            <div class="block_form_item">
                <div class="block_form_item_title">
                    付款單日期
                    <span class="required">*</span>
                </div>
                <div class="dateBox">
                    <div class="picker">
                        <input type="date" id="src_dateFrom" name="dateFrom" class="datepicker">
                        <i class="far fa-calendar"></i>
                    </div>
                     -
                     <div class="picker">
                        <input type="date" id="src_dateTo"  name="dateTo" class="datepicker">
                        <i class="far fa-calendar"></i>
                    </div>
                </div>
            </div>

            <div class="block_form_item">
                <div class="block_form_item_title">
                    員工存入日期
                    <span class="required">*</span>
                </div>
                <div class="item_picker">
                    <input type="date" id="deposit_date" name="deposit_date" class="block_form_item_input datepicker" required>
                    <i class="far fa-calendar"></i>
                </div>
            </div>

            <div class="block_form_item" id="CardType">
                <div class="block_form_item_title">
                    匯款或退款
                    <span class="required">*</span>
                </div>
                <div class="block_form_item_radio">
                    <input class="radio-input" type="radio" name="cashType" id="Remit" value="remit"
                        class="block_form_item_radio" checked>
                    <label class="radio-label" for="Remit"><span class="radio-button"></span>匯款</label>
                    <div class="radio_bgc"></div>
                </div>
                <div class="block_form_item_radio">
                    <input class="radio-input" type="radio" name="cashType" id="Refund" value="refund"
                        class="block_form_item_radio">
                    <label class="radio-label" for="Refund"><span class="radio-button"></span>退款</label>
                    <div class="radio_bgc"></div>
                </div>
            </div>

            <div class="buttons">
                <button class="button" id="Submit" type="submit">取付款單</button>
            </div>
        </form>
    </div>

    <div class="block cashpymt_getList" style="display: none;">
        <div class="outerLoading">
            <div class="loading"></div>
        </div>
        <div class="list"></div>
       
        <div class="buttons">
            <button class="button" id="GetList_Submit">取回付款單</button>
            <button class="button" id="GetList_Cancel">取消</button>
        </div>
    </div>

    <div class="block cashpymt_send" data-num={{ cashPymt_id }} style="display: none;">
        <h1 class="title">現金匯款單</h1>
        <div class="signNumber">
            <span id="cashpymt_id"></span>
        </div>
        <div class="list"></div>
       
        <div class="buttons">
            <button class="button" id="Send_Submit">送出</button>
            <button class="button" id="Send_Cancel">取消</button>
        </div>
    </div>
</section>

<div id="alert">
    <div class="alertBg"></div>
    <div class="alertmain">
        <svg width="100" height="100" class="icon">
            <circle cx="50" cy="50" r="45" class="circle" />
            <polyline fill="none" stroke="#fff" stroke-width="10" points="30,55 45,70 70,35" stroke-linecap="round" stroke-linejoin="round" class="tick" />
            <g class="fork">
                <polyline fill="none" stroke="#fff" stroke-width="10" points="35,65 65,35" stroke-linecap="round" />
                <polyline fill="none" stroke="#fff" stroke-width="10" points="35,35 65,65" stroke-linecap="round" />
            </g>
        </svg>
        <div class="loading"></div>
        <h3>已送出!</h3>
        <div class="errorBlock">
            <h5 class="errorBlock_btn">查看更多 ▼</h5>
            <span class="errorBlock_text"></span>
        </div>
    </div>
</div>

<script src="{% static 'js/reference/jquery.js' %}"></script>
<script src="{% static 'js/api.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


{% endblock %}

eforminternal/templates/myweb/tab_daily.html
{% extends "myweb/base.html" %}

{% block content %}
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/reference/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/reference/fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/daily.css' %}">
</head>
<section class="daily page" id="Daily">
    <div class="block">
        <h1 class="title" id="daily_title" data-num={{ item_num }}>每日必填</h1>
        <p class="title_signNumber" id="item_num"></p>
        <form class="block_form" method="POST">
            <div class="block_form_item">
                <div class="block_form_item_title">
                    分店名稱
                    <span class="required">*</span>
                </div>
                <div class="selectBox">
                    <i class="fas fa-angle-down"></i>
                    <select name="unit" id="store_id" class="block_form_item_select storeList" required>
                    </select>
                </div>
                
            </div>
            <div  class="block_form_item" >
                <div class="block_form_item_title">
                    日期
                </div>
                <input name="input_date" id="r_date" type="text" class="block_form_item_input form_today readonly" required readonly>
            </div>
            <div class="block_form_item">
                <div class="block_form_item_title">
                    上班人數
                    <span class="required">*</span>
                </div>
                <input name="onduty" id="on_duty" type="tel" class="block_form_item_input" required>
            </div>
            <div class="block_form_item">
                <div class="block_form_item_title">
                    出勤人員名單
                    <span class="required">*</span>
                </div>
                <input name="onduty2" id="on_duty_name" type="text" class="block_form_item_input" required>
            </div>
            <div class="buttons">
                <button class="button" id="Submit">送出</button>
                <div class="button" id="Search" data-type="false">查詢前 10 筆資料</div>
            </div>
            {% csrf_token %}
        </form>
    </div>
     <div id="dailyList" style="display: none;">
        <div class="list_title">最近 10 筆資料</div>
        <div class="outerLoading" >
            <div class="loading"></div>
        </div>
        <div class="list_main"></div>
    </div>
</section>

<div id="alert">
    <div class="alertBg"></div>
    <div class="alertmain">
        <svg width="100" height="100" class="icon">
            <circle cx="50" cy="50" r="45" class="circle" />
            <polyline fill="none" stroke="#fff" stroke-width="10" points="30,55 45,70 70,35" stroke-linecap="round" stroke-linejoin="round" class="tick" />
            <g class="fork">
                <polyline fill="none" stroke="#fff" stroke-width="10" points="35,65 65,35" stroke-linecap="round" />
                <polyline fill="none" stroke="#fff" stroke-width="10" points="35,35 65,65" stroke-linecap="round" />
            </g>
        </svg>
        <h3>已送出!</h3>
    </div>
</div>

<script src="{% static 'js/reference/jquery.js' %}"></script>
<script src="{% static 'js/api.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

{% endblock %}